import { Button, VerticalBox } from "std-widgets.slint";


export component AppWindow inherits Window {
    
    width: 300px;
    height: 150px;
    title: "Litecoin";
    in-out property <string> price: "0";
    callback request-increase-value();

    VerticalBox {
        spacing: 1px;
        VerticalLayout {
            alignment: LayoutAlignment.center;
            HorizontalLayout {
                HorizontalLayout {
                    spacing: 10px; 
                    Image {
                        source: @image-url("icons/logo.png");
                        width: 25px;
                    }  
                    Text {
                        font-size: 24px;
                        text: "Laitcoin";
                        vertical-alignment: center;
                    }
                }  
                
                Text {
                    font-size: 24px;
                    horizontal-alignment: right;
                    text: "$\{root.price}";
                }
            }           
        }

        

        Button {
            height: 50px;
            primary: true;
            text: "Refresh";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
